### ISSUE TITLE
gae: Property has bad type datastore.indexValue

### ISSUE THREAD

**Issue by vadimsht** [luci/gae#1]
I'm using github.com/luci/gae/impl/prod on devserver.

One of my queries used to work fine, then I did some unrelated changes (at least I don't see how they are related) and same query started to fail with "gae: Property has bad type datastore.indexValue".

My entity is:
```
type jobEntity struct {
	_kind string `gae:"$kind,CronJob"`

	JobID string `gae:"$id"`
	ProjectID string
	Enabled bool

	... other scalar fields including one substruct ...
}
```

Failing query is somewhat unusual...

	ds := datastore.Get(c)
	q := ds.NewQuery("CronJob").
		Filter("Enabled =", true).
		Project("ProjectID").
		Distinct()
	entities := []jobEntity{}
	if err := ds.GetAll(q, &entities); err != nil {
		return nil, err
	}

index.yaml:

```
indexes:

- kind: CronJob
  properties:
  - name: Enabled
  - name: ProjectID
```

It worked, and then stopped :-/ I'm not sure what I changed... Clearing datastore on devserver didn't help. Other simpler queries work, e.g. this one works:

	q := ds.NewQuery("CronJob").
		Filter("Enabled =", true).
		Filter("ProjectID = ", projectID)
	
Am I missing something stupid? :)

If I remove Distinct() it still fails in same way. If I remove both Project().Distinct(), it works.

**Comment by vadimsht** [comment]
PS: it works on real prod datastore :-/

**Comment by riannucci** [comment]
Looks like a bug in projections probably. If you could add a test which fails, I can fix it (though I could probably add a test given this bug report too :) )

**Comment by vadimsht** [comment]
I suspect it's something related to dev_appserver mocks: the bug does not reproduce when I run code on real GAE. I haven't tried memory implementation yet.

IIUC, we do not have unittests against dev_appserver currently?

**Comment by riannucci** [comment]
Correct we do not currently have dev appserver tests.

My guess is that it is maybe prompting you to add an index?

R

**Comment by vadimsht** [comment]
Nope. It fails cleanly with "Need index" error if it requires an index. (And I've added this required index already).

I'll try to dumb protos returned by dev_appserver. I expect there's some unexpected crap there.

**Comment by riannucci** [comment]
Oh wait this is impl/prod??? I just use the SDK methods. Maybe it's
building a bad ProperyList?

**Comment by vadimsht** [comment]
Here: https://github.com/luci/gae/blob/master/impl/prod/raw_datastore_type_converter.go#L22

props has single property {Name:ProjectID Value:{value:0xc208135db0} NoIndex:false Multiple:false} where Value has type datastore.indexValue. And this type is not recognized by the rest of the code.

**Comment by vadimsht** [comment]
Stack trace for this call:
```
	/Users/vadimsh/infra-git/infra/go/src/github.com/luci/gae/impl/prod/raw_datastore_type_converter.go:50 +0x626
google.golang.org/appengine/datastore.loadEntity(0x3d0320, 0xc208036cd0, 0xc2080df500, 0x0, 0x0)
	/Users/vadimsh/infra-git/infra/go/.vendor/src/google.golang.org/appengine/datastore/load.go:224 +0xed
google.golang.org/appengine/datastore.(*Iterator).Next(0xc2080948c0, 0x3d0320, 0xc208036cd0, 0xc2080948c0, 0x0, 0x0)
	/Users/vadimsh/infra-git/infra/go/.vendor/src/google.golang.org/appengine/datastore/query.go:580 +0xb3
github.com/luci/gae/impl/prod.rdsImpl.Run(0x78d5b8, 0xc2081040c0, 0x0, 0x0, 0x78d950, 0xc208163c20, 0xc208104240, 0x0, 0x0)
	/Users/vadimsh/infra-git/infra/go/src/github.com/luci/gae/impl/prod/raw_datastore.go:145 +0x1bb
github.com/luci/gae/impl/prod.(*rdsImpl).Run(0xc20806f520, 0x78d950, 0xc208163c20, 0xc208104240, 0x0, 0x0)
	<autogenerated>:120 +0xd0
github.com/luci/gae/service/datastore.(*checkFilter).Run(0xc208104120, 0x78d950, 0xc208163c20, 0xc208104240, 0x0, 0x0)
	/Users/vadimsh/infra-git/infra/go/src/github.com/luci/gae/service/datastore/checkfilter.go:36 +0x11b
github.com/luci/gae/service/datastore.(*datastoreImpl).GetAll(0xc20807d790, 0x78d950, 0xc208163c20, 0x2efec0, 0xc20806f540, 0x0, 0x0)
	/Users/vadimsh/infra-git/infra/go/src/github.com/luci/gae/service/datastore/datastore.go:120 +0x647
github.com/luci/luci-go/appengine/cmd/cron/engine.(*engineImpl).GetAllProjects(0xc20800d950, 0x78d5b8, 0xc2081040c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/vadimsh/infra-git/infra/go/src/github.com/luci/luci-go/appengine/cmd/cron/engine/engine.go:123 +0x2ec
```

**Comment by vadimsht** [comment]
For the record: it DOES happen on real GAE too. Not devserver specific.

**Comment by riannucci** [comment]
Hm.. line 50 doesn't line up with my version of the code... Did you add stuff? Is it actually line 44: https://github.com/luci/gae/blob/master/impl/prod/raw_datastore_type_converter.go#L44 ?

**Comment by vadimsht** [comment]
I had some loops to grab debug output there to see what's going on (because, you know, Go + debugger => non existent).

**Comment by riannucci** [comment]
Yeah this is definitely fixable: I have half a patch already.

**Comment by vadimsht** [comment]
No rush :) I degraded my query to non-projection one, I'm not blocked on this.

**Comment by riannucci** [comment]
CL to fix is here: https://codereview.chromium.org/1336443003

**Comment by riannucci** [comment]
Fixed :)

**Comment by vadimsht** [comment]
My .Project(...).Distinct() query works now :relieved:

**Comment by riannucci** [comment]
:+1: :smile:
