### ISSUE TITLE
Handle unexpected entity fields more gracefully

### ISSUE THREAD

**Issue by vadimsht** [luci/gae#13]
Imagine I'm changing my entity struct by removing a field I do not care about anymore. Suddenly all my Get's "fail" with ErrFieldMismatch. 

Coming from Python GAE, I expect Get() to silently drop unknown field. Or put it into some less-structured area ala ndb's Expando class.

What I do not want to do is to check every Get() error against ErrFieldMismatch and whitelist of fields I do not care about...

**Comment by riannucci** [comment]
Proposal:

```go
type Bird struct {
  Name string
  // deleted: `Type string`
}

type Elephant struct {
  Name string
  // deleted: `Memories string`
  Extra ds.PropertyMap `gae:",extra"`
}

type MyThing struct {
  Normal string
  Nested Bird
  Ele    Elephant
  Extra  ds.PropertyMap `gae:",extra"`
}

// Extras go into the closest extra walking up the stack, so:
// MyThing.Extra["Nested.Type"] = []Property{"value"}
// MyThing.Ele.Extra["Memories"] = []Property{"value"}
```

**Comment by vadimsht** [comment]
lgtm

Entities with ",extra" will round-trip loss-less?
Entities without ",extra" will return ErrFieldMismatch on data loss as they do now?

**Comment by riannucci** [comment]
yes, that would be the intent

**Comment by vadimsht** [comment]
Does mode "always drop extra on Save" make sense?

Maybe 

```go
type Entity struct {
  extra ds.PropertyMap `gae:",extra,skip"
}
```

or something..

**Comment by riannucci** [comment]
you mean:

```go
type Entity struct {
  Extra ds.PropertyMap `gae:"-,extra"`
}
```

`-`: No name, current way to skip a field.
`extra`: Dump extras on load

maybe?

**Comment by vadimsht** [comment]
Yeah. Any way to say "I don't care about old fields anymore".

So if I used to python semantic I'll just add this to every entity:

```go
type Entity struct {
  // Silently drop unknown fields.
  _ ds.PropertyMap `gae:"-,extra"`
}
```

(Is "_" a valid identifier in structs?..)

**Comment by riannucci** [comment]
I guess we could special case it, but in general, fields need to be exported for StructPLS to write into them. If you really want to just... black hole everything, I guess that form would work. And yes, `_` is a valid field name. Basically it would read that as "Put all extra fields here. When you try to put them, ignore them". You wouldn't need the `-` in the tag though, since the field is unexported.

**Comment by riannucci** [comment]
CL to fix here: https://chromiumcodereview.appspot.com/1525453002

**Comment by riannucci** [comment]
Fixed :)
