### ISSUE TITLE
Need an impl/memory for User service

### ISSUE THREAD

**Issue by riannucci** [luci/gae#24]
Maybe just add a Testing() interface that looks like:

```go
type Testing interface {
  SetUser(*User)

  Login(email string, admin bool)
}
```

And provide some fake Login/Logout url values. Do we need more than that? I don't fully understand what would be useful around the oauth stuff though.

**Comment by riannucci** [comment]
@vadimsht wdyt?

**Comment by vadimsht** [comment]
What does "Login" do? 

SetUser() and making LoginURL()\LogoutURL() return fake values is good enough, IMHO (for OAuth stuff too).

**Comment by riannucci** [comment]
Login would be a shorthand invocation of SetUser that filled in the rest of the user fields with stuff derived from email and admin.

**Comment by riannucci** [comment]
CL: https://chromiumcodereview.appspot.com/1522783002

**Comment by riannucci** [comment]
done
