### ISSUE TITLE
Support Remote API

### ISSUE THREAD

**Issue by riannucci** [luci/gae#33]
https://cloud.google.com/appengine/docs/go/tools/remoteapi

**Comment by riannucci** [comment]
@SlothNinja FYI

**Comment by riannucci** [comment]
Potential implementation, no tests: https://chromiumcodereview.appspot.com/1549223002

**Comment by erikus** [comment]
Nice! I was just wishing for this yesterday.

**Comment by riannucci** [comment]
Done. I only tested against dev_appserver, but it seems to work. Recipe for success against dev_appserver:

1. Add app.yaml magic: 

    ```yaml
    handlers:
    - url: /_ah/remote_api
      script: _go_app
      secure: always
    ```

2. Create a new `*http.Client` with a cookiejar (e.g. from `"net/http/cookiejar"`)

    ```go
    jar, err := cookiejar.New(nil)
    if err != nil { panic(err) }
    client := &http.Client{Jar: jar}
    ```

3. Use said client to login to dev_appserver by hitting `_ah/login`

    ```go
    u := fmt.Sprintf("http://localhost:8080/_ah/login?%s", url.Values{
      "email":  {"test@example.com"},
      "action": {"Login"},
      "admin":  {"True"},
    }.Encode())
    rsp, err := client.Get(u)
    if err != nil { panic(err) }
    rsp.Body.Close()
    ```

4. Use your client to make a new remote context

    ```go
    c, err := prod.UseRemote(context.Background(), "localhost:8080", client)
    if err != nil { panic(err) }
    ```

5. Use your new Context with any of the `luci/gae/service`'s

**Comment by riannucci** [comment]
Oh, and to hit real appengine, you'll need to re-upload your app after the yaml change, and you can pass nil for the client to have it do local oauth client magic (probably... untested).
