### ISSUE TITLE
Time-based inequality queries don't seem to work in impl/memory.

### ISSUE THREAD

**Issue by danjacques** [luci/gae#34]
Maybe I'm doing something wrong here, but I seem to be getting bad results with time-based inequality queries in impl/memory. For example:

```go
package main

import (
        "fmt"
        "time"

        "github.com/luci/gae/impl/memory"
        "github.com/luci/gae/service/datastore"
        "golang.org/x/net/context"
)

type MyType struct {
        ID   string `gae:"$id"`
        Date time.Time
}

func main() {

        c := context.Background()
        c = memory.Use(c)
        now := time.Date(2015, 1, 1, 0, 0, 0, 0, time.UTC)

        di := datastore.Get(c)
        for _, t := range []*MyType{
                {ID: "foo", Date: now.Add(-time.Second)},
                {ID: "bar", Date: now.Add(2 * -time.Second)},
                {ID: "baz", Date: now},
                {ID: "qux", Date: now.Add(time.Second)},
        } {
                if err := di.Put(t); err != nil {
                        panic(err)
                }
        }
        di.Testable().CatchupIndexes()

        q := datastore.NewQuery("MyType").
                Lt("Date", now)

        fmt.Println("Records <", now)
        err := di.Run(q, func(t *MyType) {
                fmt.Println("GOT:", t.ID, t.Date, t.Date.Before(now))
        })
        fmt.Println("Result:", err)
}
```

In this example, I would expect it to return "foo" and "bar", since both of those have Date properties that are < `now`. However, when run, all four `MyType` entries are returned.

I'm going to burrow deeper, but I wanted to post to confirm whether my expectations are correct.

**Comment by danjacques** [comment]
That was fun to track down. Prospective fix: https://chromiumcodereview.appspot.com/1550903002/

**Comment by riannucci** [comment]
The bug here is not that PropertyMaps record times as times, but that indexes use the byte values directly from the property map; PTTime values need to be projected to PTInt before being serialized in the indexes. See the equivalence classes here: https://cloud.google.com/appengine/docs/go/datastore/entities#Go_Value_type_sort_order

I think we're doing the byte sequences correctly, but it'd be good to check (and make sure we have a test for it)
