### ISSUE TITLE
dscache spams the logs 

### ISSUE THREAD

**Issue by riannucci** [luci/gae#35]
```
2015/12/31 20:29:35 WARNING: dscache: GetMulti: memcache.AddMulti :: {"error":"memcache: item not stored"}
```

These log messages are not helpful; they simply indicate that the item already exists in memcache, and so we couldn't add a lockitem for them. I vote to remove the log line entirely.

**Comment by danjacques** [comment]
Remove, demote to debug, either one works.

**Comment by riannucci** [comment]
but you made debug the default level :stuck_out_tongue: .

**Comment by danjacques** [comment]
AppEngine told me it was OK.

**Comment by riannucci** [comment]
I'm sure it's OK (as in: appengine won't go up in flames), this log item is still spammy, and we have no way (in any code) to include potentially spammy debugging logs without also spamming ALL of the logs, since debug is the default.
