### ISSUE TITLE
Add support for appengine.BackgroundContext

### ISSUE THREAD

**Issue by shkw** [luci/gae#39]
Hi,

As of now, there seems to be no way in `impl/prod` to work with a context returned by [appengine.BackgroundContext](https://godoc.org/google.golang.org/appengine#BackgroundContext).
Since I wanted to use `luci/gae` with the background context on Managed VMs, I made a small change at shkw/gae@fb3af9677c62787d6b8c522c8400684d5c622a6b to achieve it for now.

I believe it would be really useful if `luci/gae` could officially support this feature.

**Comment by riannucci** [comment]
Hey @shkw!

I could accept your code if you accept the Google CLA (see the Contributing section in the main [README](https://github.com/luci/gae)).

Otherwise I'll take a look at reimplementing this directly.

**Comment by riannucci** [comment]
Actually this is simple enough that I'll just reimplement. CL coming right up (though I haven't looked at your code, so I don't know if it's actually the same or not :)).

**Comment by riannucci** [comment]
CL https://chromiumcodereview.appspot.com/1630833002/ landing shortly.

**Comment by shkw** [comment]
Thanks for adding the support so quickly.
I could see that https://chromiumcodereview.appspot.com/1630833002/ is completely same as my code.
