### ISSUE TITLE
Rename service.Get(c) to service.Client(c)

### ISSUE THREAD

**Issue by riannucci** [luci/gae#47]
Then the currently-confusing:

```go
err := datastore.Get(c).Get(entity)
```

Turns into the much less confusing

```go
err := datastore.Client(c).Get(entity)
```

That would apply to all services

**Comment by riannucci** [comment]
Yes, this would break API compatibility, but [THIS PACKAGE HAS NO API COMPATIBILITY GUARANTEES. USE UNPINNED AT YOUR OWN PERIL.](https://github.com/luci/gae#this-package-has-no-api-compatibility-guarantees-use-unpinned-at-your-own-peril)

😄

But, really, I think staying on top of junky API decisions like this will be all-around better in the long term.

**Comment by danjacques** [comment]
Maybe `datastore.Service` or `datastore.Iface`?

**Comment by riannucci** [comment]
Well it returns an implementation of the client, so I don't think IFace is
good (also datastore.Interface already means something). It's also not
really a service (though it does have a 'connection' to the service). I
think the analogy to the pRPC client is what I was going for.

**Comment by danjacques** [comment]
This will be obsoleted by #53.
