### ISSUE TITLE
Make Get, Put, Delete variadic on datastore.Interface

### ISSUE THREAD

**Issue by riannucci** [luci/gae#51]
Frequently I find myself doing:

```go
a := &Model{}
b := &OtherModel{}
err := ds.GetMulti([]interface{}{a, b})
```

It would be a lot nicer to do:

```go
a := &Model{}
b := &OtherModel{}
err := ds.Get(a, b)
```

This API change would be backwards-compatible: Get would return a single error in the event that you do it with a single entity, and a multi-error if you pass in multiple. Modifying GetMulti to have this interface would break compatibility, and it would preclude you from doing things like passing a `[]*Model`, which is a supported usecase of GetMulti (and avoids some reflection inefficiencies too).

**Comment by danjacques** [comment]
After some discussion, the plan is to remove the `*Multi` versions of these calls from the public interface and make the single-argument versions variadic. Each will operate in one of two modes:
* If you give them a single argument, they will return a single error.
* If you give them a slice of entity types, or multiple arguments, they will process them in the same manner as GetMulti and return a MultiError.
* If any of these "single arguments" is actually a slice of entities, the error returned for them will be a MultiError. This means that `Get(sliceA, sliceB, sliceC)` will return `[]MultiError{[]MultiError{sliceA}, []MultiError, []MultiError}`.

This will maintain compatibility with current `Get` and `GetMulti` calls. It will also allow the user to use their own native slices and representations more seamlessly.
