### ISSUE TITLE
Use math/rand's Read() method for gae/filter/dscache in place of crappyNonce

### ISSUE THREAD

**Issue by riannucci** [luci/gae#55]
Right now we use mathrand just because it _used_ to be the only one that was mocked for testing. Since that's no longer the case, we should use cryptorand instead.

**Comment by vadimsht** [comment]
IMHO, randomizing cache expiration is not crypto-related activity. Mathrand is good enough.

**Comment by riannucci** [comment]
It's for the placeholder key that goes inside the memcache value. It's more about "this is sketchy code that declares itself as such, might as well make it non-sketchy"

**Comment by danjacques** [comment]
`math/rand` isn't low-quality PRNG, it's just not cryptographically strong. Generally this comes at the expense of additional resources or computation. Unless there is a security risk here or `math/rand` is a junk PRNG, I'm with @vadimsht in sticking with `math/rand`.

**Comment by riannucci** [comment]
It was more about getting rid of this abomination than anything else: https://github.com/luci/gae/blob/master/filter/dscache/support.go#L96

It uses math/rand to generate a random []byte. This feels pretty ugly to me, especially since crypto/rand does this as its primary interface. The only reason it was done this way was out of laziness to take advantage of the math/rand mock that existed at the time.

Said another way: if we were implementing it again, and the crypto/rand mock already existed, we would never consider writing that function.

**Comment by danjacques** [comment]
Hmm, why aren't we just using `math/rand`'s [Read](https://golang.org/pkg/math/rand/#Rand.Read)?

**Comment by riannucci** [comment]
Whaaaaaaat. That's new in 1.6. We should definitely use that.

**Comment by danjacques** [comment]
Learn2`Read`
