### ISSUE TITLE
Question: datastore Get on key and the result being populated on target struct.

### ISSUE THREAD

**Issue by bsr203** [luci/gae#57]
Hi,

I am trying to integrate `luci/gae` into my project, and work around the API differences from standard SDK, except `Get` so far.

It would be a major change if I have to get an entity by filling the target with ID as in [here](https://github.com/luci/gae/blob/master/service/datastore/datastore_test.go#L1017)

Instead, I want to get an entity with key. The rawInterface gives the result in `PropertyMap`, and if not sure any API there to convert `PropertyMap` to dst struct. I see `inst.Get` uses [multiArg](https://github.com/luci/gae/blob/master/service/datastore/multiarg.go) to do this mapping, but no public API. Also, going through `multiarg.go`, it is non trivial to do this mapping.

so, how to use `Get` like

```
Get(key *Key, dst ...interface{}) error`
```

cc @danjacques 

thanks,
bsr.

**Comment by riannucci** [comment]
You can use `GetPLS` to get a PropertyLoadSaver for your struct, which is the high-level API for all the multiArg stuff, and then Get into a PropertyMap. It's not going to be very pretty, but it would work. Something like:

```go
pmap := PropertyMap{}
pmap.SetMeta("key", <key>)
if err := ds.Get(pmap); err != nil { panic(err) }
realDest := &MyStruct{}
pls := GetPLS(realDest)
pls.Load(pmap)
ds.PopulateKey(realDest, GetMetaDefault(pls, "key", (*Key)(nil))
```

Something like that. The API was definitely designed to be used with the embedded-keys way of doing things though.

**Comment by bsr203** [comment]
Thanks Robert. Inserting a single entity and retrieving it is working. Can you please check what am I doing wrong with `getAll` and `queryRaw` below. I expect both of them returns 5 entities as limited by the query.

```
package init

import (
	"fmt"
	"net/http"
	"os"

	"github.com/luci/gae/impl/prod"
	"github.com/luci/gae/service/datastore"

	"golang.org/x/net/context"
)

func init() {
	http.HandleFunc("/", root)
}

// User represent a user in the system
type User struct {
	ID    string `gae:"$id"`
	Value string
}

func root(w http.ResponseWriter, r *http.Request) {
	c := prod.Use(context.Background(), r)
	run(c, w)
}

func run(c context.Context, w http.ResponseWriter) {
	fmt.Println("put")
	u := &User{ID: uuid(), Value: "Hello World"}
	check(put(c, u))
	u2 := User{ID: u.ID}
	check(get(c, &u2))
	fmt.Printf("u2: %+v\n", u2)

	fmt.Println("putMulti")
	var uu []User
	for i := 0; i < 10; i++ {
		uu = append(uu, User{ID: uuid(), Value: fmt.Sprintf("Hello %d", i)})
	}
	check(putMulti(c, uu))

	fmt.Println("getAll")
	uuOutput := []User(nil)
	q := datastore.NewQuery("").Limit(5)
	check(getAll(c, q, &uuOutput))
	fmt.Printf("uuOutput: %+v\n", uuOutput)

	fmt.Println("queryRaw")
	fin, err := q.Finalize()
	check(err)
	fmt.Printf("out: %+v", queryRaw(c, fin))
}

func put(c context.Context, d interface{}) error {
	return datastore.Get(c).Put(d)
}

func putMulti(c context.Context, d interface{}) error {
	return datastore.Get(c).PutMulti(d)
}

func get(c context.Context, d interface{}) error {
	return datastore.Get(c).Get(d)
}

func getAll(c context.Context, q *datastore.Query, d interface{}) error {
	return datastore.Get(c).GetAll(q, d)
}

// func query()  {
// 	datastore.Get(c).Run(q, func(u User) {
// 	})
// }

func queryRaw(c context.Context, q *datastore.FinalizedQuery) []datastore.PropertyMap {
	var out []datastore.PropertyMap
	cb := func(key *datastore.Key, val datastore.PropertyMap, getCursor datastore.CursorCB) error {
		fmt.Printf("key: %+v, val: %+v", key, val)
		out = append(out, val)
		return nil
	}

	check(datastore.Get(c).Raw().Run(q, cb))
	return out
}

func uuid() string {
	f, err := os.OpenFile("/dev/urandom", os.O_RDONLY, 0)
	check(err)
	b := make([]byte, 16)
	f.Read(b)
	f.Close()
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:])
}

func check(err error) {
	if err != nil {
		panic(err)
	}
}
```
api_test.go

```
package init

import (
	"net/http/httptest"
	"testing"

	"github.com/luci/gae/impl/memory"

	"golang.org/x/net/context"
)

func TestRunHello(t *testing.T) {
	c := memory.Use(context.Background())
	var rec httptest.ResponseRecorder
	run(c, &rec)

}
```

to run. on the src folder.

```
go test ./... -v
```

**Comment by riannucci** [comment]
Ah, I think you're running into the explicit index handling in the in-memory implementation. The in-memory implementation requires that you explicitly manipulate the indexes in the test. Take a look at https://godoc.org/github.com/luci/gae/service/datastore#Testable which is the interface for datastore that lets you adjust this.

For simple tests, you can just do:

```go
ds := datastore.Get(c)
ds.Testable().Consistent(true)
ds.Testable().AutoIndex(true)
// your test will now behave as if the indexes are always fully-consistent
```

If you want fine-grained control over your index state in the test, you can use the other methods in the Testable interface to manipulate the state of the datastore index (e.g. calling `CatchupIndexes` explicitly in the tests, or taking/setting index snapshots).

**Comment by riannucci** [comment]
To be clear; in your current test, the Put/Get operations are fully consistent (as they would be in the real datastore), but the query operations (which require an index) are in the not-yet-consistent state. If you did an ancestor query in the test right now, that would reflect the entities present in that entity group (since ancestor queries are consistent by default).

Also as a general matter of style, we usually create a datastore client (e.g. `datastore.Get(c)`) once per function body, and then re-use that for all operations in that function. There's no requirement or benefit that you make a new datastore client for each operation :).

**Comment by bsr203** [comment]
Thanks Robert. One step closer :-) 

Now, everything in the above example works, except `getAll`

which gives below error. I see each property (struct field) has an associated `__version__` returned as a result of query, and not sure whether I need to manually prune it, or better way to do `getAll`
```
getAll
--- FAIL: TestRunHello (0.00s)
panic: gae: cannot load field "__version__" into a "init.User": no such struct field (and 1 other error) [recovered]
	panic: gae: cannot load field "__version__" into a "init.User": no such struct field (and 1 other error)

goroutine 19 [running]:
panic(0x5e5b40, 0xc8201e19a0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6

```

thanks again. bsr.

**Comment by bsr203** [comment]
Setting `DisableSpecialEntities(true)` disabled `__version__`, and looking at source code, it is maintained by this library. I will ask a separate question about metadata collected by this lib. thanks again for your time and help.

**Comment by riannucci** [comment]
There's also this thing: https://godoc.org/github.com/luci/gae/service/datastore/dumper
which can be useful for really doing a full dump (mostly for debugging, but it could be used as a template for other sorts of dump-the-world stuff)

Note that the `__entity_group__` entities are actually emulating the real-world metadata entities (they exist in all datastores, even in Go, but don't seem to be well documented). Here's the Java doc which mentions their existence: https://cloud.google.com/appengine/docs/java/datastore/metadataqueries

Note that if you really wanted a query just for User-kind entities, you would want to do NewQuery("User"). NewQuery("") is actually kind-of special in that it will iterate over every single entity in the datastore, regardless of kind.
