### ISSUE TITLE
"Multiple" boolean is lost in translation

### ISSUE THREAD

**Issue by riannucci** [luci/gae#58]
@rryk discovered this bug ([crbug.com/644815](https://crbug.com/644815))

Apparently the 'Multiple' bool in the Property object in the original SDK actually has semantic meaning apart from just "this is multiple". Specifically today

```go
type Foo struct {
  ID int64 `gae:"$id"`
  Something []int
}

f := &Foo{Something: []int{1}}
ds.Put(ctx, f)
```

Will record a Foo with a non-multiple Something field. This causes problems when loading this Foo from non-go languages like python when the python model claims that Something is a repeated field.

This is lost in translation when `f` is serialized to a PropertyMap. At that point the 'multiple-ness' of Something is lost.

@danjacques proposes that we change PropertyMap to something like:

```go
type PropertyData interface{
  // Returns (data[0], wasMultiple)
  Single() (Property, bool)

  // Returns (data -> []Property, wasMultiple)
  Multiple() ([]Property, bool)
}
type PropertyList []Property  // implements PropertyData
type Property interface{}       // implements PropertyData 
type PropertyMap map[string]PropertyData
```

Which will allow the lower implementations to correctly distinguish the single-value-in-a-multi-slot vs a single-value-in-a-single-slot cases.

**Comment by danjacques** [comment]
I don't think `Single` is particularly useful given `Multiple`, and I'm concerned that `Multiple` allows you to express multiple values with `wasMultiple` set to false.

After discussion, propose using a tag:
```go
type PropertyData interface {
  isAPropertyData()
}
```

**Comment by riannucci** [comment]
Yep, tagged union sounds even better :)
