### ISSUE TITLE
taskqueue.Add must verify taskname

### ISSUE THREAD

**Issue by kdy1997** [luci/gae#61]
appspot.com returns error from rpc, but currently in memory implementation does not check it.

See https://cloud.google.com/appengine/docs/python/taskqueue/

> When you create a new task, App Engine assigns the task a unique name by default. You can assign your own name to a task by using the name parameter.

> A task name must be unique within a queue. If you try to add another task with the same name to a the queue, the operation will fail. After a task is removed from a queue you can't insert a task with the same name into the queue until 10 days have passed. A task name can contain uppercase and lowercase letters, numbers, underscores, and hyphens. The maximum length for a task name is 500 characters.

> Recommended: Let App Engine generate task names automatically.

**Comment by danjacques** [comment]
The task name is validated [here](https://github.com/luci/gae/blob/cfd4c03f8de6f353360064aca2d2fcf517bedf8b/impl/memory/taskqueue_data.go#L175).

Can you provide a test case that demonstrates this failure? From what I can see, the task name is validated and test code asserts that this validation is working.

**Comment by kdy1997** [comment]
Oh, I noticed that my test code does not have a test for the case. Sorry for my mistake.
I deployed it as test suceed and because I got error on appspot while testing my data, I thought it was bug.
