### ISSUE TITLE
Cost-optimize single-entity "Exists" by using a keys-only query?

### ISSUE THREAD

**Issue by danjacques** [luci/gae#62]
Currently, `Exists` calls turn into a raw datastore `GetMulti` that simply discards the response data. However, for a single-entity `Exists` (e.g., does specifically key X exist?), this could be further optimized into a keys-only query for that entity. This would turn the cost for a single-entity existence check to zero, instead of a full datastore Get.

This should work both transactionally and non-transactionally. This would work for both `impl/prod` and `impl/cloud`. Also note that queries are potentially slower than direct `Get`. I suppose a filter would be best here, then, although it would have to live at a layer below `dscache` else we're being wasteful. WDYT?

**Comment by vadimsht** [comment]
Does keys only query guarantee strong consistency semantics as regular Get does?

E.g. if I Put an entity, and immediately do keys-only query, does it find it?

I assume it does if using ancestor query? (How do ancestor queries for root-level entity keys work?).

**Comment by maruel** [comment]
Filter may not be valid. It happens for ancestor-less query.

Le 12 oct. 2016 3:03 PM, "Vadim Shtayura" <notifications@github.com> a
écrit :

**Comment by danjacques** [comment]
This seems like a micro-optimization with some potential nuanced failure cases. With `dscache` filter, an `Exists` check should generically be free (1 memcache hit) anyway. I'll close this idea; feel free to re-open if someone thinks there is utility here.
