### ISSUE TITLE
unused  argument

### ISSUE THREAD

**Issue by bsr203** [luci/gae#67]
Hi,
I was trying to use `Raw. GetMulti` and found an unused argument, [_meta](https://github.com/luci/gae/blob/master/impl/prod/raw_datastore.go#L119),  as part of public API. can we remove it?

thanks.
bsr

**Comment by riannucci** [comment]
It's there for filters between the user layer and the implementation to act on, e.g. https://github.com/luci/gae/blob/master/filter/dscache/ds.go#L39. That said, you can just provide nil, as https://github.com/luci/gae/blob/272b5f2351009dfef30f2a0f4a4681df4a8725ab/service/datastore/raw_interface.go#L98 will always return an "unset" value if the metas value is empty/nil.

**Comment by bsr203** [comment]
thanks.
