### ISSUE TITLE
Weird interaction between txnBuf and namespaces

### ISSUE THREAD

**Issue by vadimsht** [luci/gae#69]
luci-go's "gaesettings" module is using following code to "break out" of transactions and namespaces:

```
func defaultContext(c context.Context) context.Context {
	return ds.WithoutTransaction(info.MustNamespace(c, ""))
}
```

If uses `defaultContext(c)` in simple datastore.Get to grab an entity with settings.

It doesn't work if c is transactional context with non-default namespace and txnBuf filter installed. datastore.Get(defaultContext(...)) returns ErrNoSuchEntity.

It works as expected for:

- Namespaced transactional and non-transactional contexts.
- Non-namespaced txnBuf transactional contexts.

Repro https://codereview.chromium.org/2562203002

This hits LogDog for real: gaesettings fetches settings lazily whenever they expire. And sometimes they expire in the middle of a tumble mutation, and gaesettings module receives txnBuf namespaced context. It "fetches" empty settings from the datastore (due to this bug), and caches them in instance memory. This effectively makes the instances broken, and GAE eventually kills it after several HTTP 500 responses.

**Comment by riannucci** [comment]
Oof, this looks bad. I'll see if I can fix it today.

**Comment by riannucci** [comment]
CL to fix: https://codereview.chromium.org/2568303003
