### ISSUE TITLE
How do Query Filter and DeleteMulti method?

### ISSUE THREAD

**Issue by ryo-yamaoka** [luci/gae#71]
I saw godoc (https://godoc.org/github.com/luci/gae/service/datastore) but could not find Filter method in type Query.
Could not find DeleteMulti,  just like it.
and, error occurred in build.

```bash
"vendor/github.com/luci/gae/service/datastore".NewQuery(XXXX_KIND).Filter undefined (type *"vendor/github.com/luci/gae/service/datastore".Query has no field or method Filter)
undefined: "vendor/github.com/luci/gae/service/datastore".DeleteMulti
```

Please tell me how to do it.

thanks.

**Comment by riannucci** [comment]
For Query, you'll want to use some of the filter methods like:
  * https://godoc.org/github.com/luci/gae/service/datastore#Query.Eq
  * https://godoc.org/github.com/luci/gae/service/datastore#Query.Gt
  * https://godoc.org/github.com/luci/gae/service/datastore#Query.Gte
  * https://godoc.org/github.com/luci/gae/service/datastore#Query.Lt
  * https://godoc.org/github.com/luci/gae/service/datastore#Query.Lte

For deletion (including DeleteMulti uses), use https://godoc.org/github.com/luci/gae/service/datastore#Delete.

**Comment by ryo-yamaoka** [comment]
I understand, i will try it.
Thank you for reply! :smiley:
