### ISSUE TITLE
Add function to seed indexes from index.yml

### ISSUE THREAD

**Issue by riannucci** [luci/gae#8]

**Comment by riannucci** [comment]
Can add two functions to Testable interface:
  * `ParseIndexYAML(content io.Reader) []*IndexDefinition` 
  * `FindAndAddIndexYAML` - walks up from source filename until it finds `index.yaml` or `index.yml`, if it hits root, panic. Else, open+parse it, add all indexes you find.

**Comment by nishanths** [comment]
Related pull req: https://chromiumcodereview.appspot.com/1574353004
